config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'trainings#index'

  resources :users

  resources :trainings
  resources :training_plans, :training_plan_items

  post 'training_plan/:training_id', to: 'training_plans#add_training', as: 'add_training'
  post 'training_plan_items/:training_item_id/mark_finished', to: 'training_plan_items#mark_finished', as: 'mark_finished'
  post 'training_plan_items/:training_item_id/mark_unfinished', to: 'training_plan_items#mark_unfinished', as: 'mark_unfinished'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/training.rb
class Training < ApplicationRecord
  has_many :training_plan_items
  has_many :training_plans, through: :training_plan_items
end

app/models/training_plan.rb
class TrainingPlan < ApplicationRecord
  belongs_to :user
  has_many :training_plan_items
  has_many :trainings, through: :TrainingPlanItem
end

app/models/training_plan_item.rb
class TrainingPlanItem < ApplicationRecord
  belongs_to :training_plan
  belongs_to :training
end

app/models/user.rb
class User < ApplicationRecord
  has_one :training_plan
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    @user = current_user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/training_plan_items_controller.rb
class TrainingPlanItemsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:mark_finished, :mark_unfinished]

  def mark_finished
    TrainingPlanItem.find_by(id: params[:training_item_id]).update_attributes(finished: true, date: Time.now)

    perform_redirect #todo: in the future use react to handle front end changes instead of redirects
  end

  def mark_unfinished
    TrainingPlanItem.find_by(id: params[:training_item_id]).update_attributes(finished: false, date: nil)

    perform_redirect
  end

  def perform_redirect
    redirect_to training_plans_path
  end

  def index
  end

  def edit

  end

  def new

  end

  def update

  end

  def destroy
    @item = TrainingPlanItem.find(params[:id])

    @item.destroy
    training_plan_id= request.referrer.split('/').last
    redirect_to training_plan_path(training_plan_id)
  end
end

app/controllers/training_plans_controller.rb
class TrainingPlansController < ApplicationController
  include UsersHelper
  
  before_action :redirect_to_login_if_not_authenticated

  def index
    @training_plans = TrainingPlan.where(user_id: current_user.id)
  end

  def show
    @training_plan = TrainingPlan.where(id: params[:id]).first
    @items = TrainingPlanItem.where(training_plan_id: params[:id])
  end

  def add_training
    users_training_plan = users_training_plan(current_user.id)
    users_training_plan.training_plan_items.create(training_id: params[:training_id])
    flash[:success] = 'Added training item to default training plan for user :)'
    redirect_to trainings_path
  end

  def redirect_to_login_if_not_authenticated
    redirect_to new_user_session_path unless current_user
    # todo don't let other users see training plans that are not their own
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  include TrainingsHelper

  before_action :check_privileges, only: [:edit, :destroy]

  def check_privileges
      redirect_to current_user unless can_be_deleted_by_user?(Training.find(params[:id]))
  end

  def index
    @trainings = Training.all
  end

  def show
    @training = Training.find(params[:id])
  end

  def create
    @training = Training.new(append_database_field_before_create(training_params)) #append total_distance

    if @training.save!
      redirect_to @training
    else
      render 'new'
    end
  end

  def destroy
    training = Training.find(params[:id])
    training.destroy
    redirect_to trainings_path
  end

  private

  def training_params
    params.require(:training).permit(:title, :content, :created_by)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/training_plan_items_helper.rb
module TrainingPlanItemsHelper
  def training_plan_item_status(item)
    return 'nil' if item.finished.nil?
    return item.finished ? 'Finished' : 'Planned'
  end

  def total_distance_in_completed_trainings(training_items)
    training_items.select(&:finished).inject(0) { |sum, item| sum+ item.training.total_distance}
  end

  def total_number_of_completed_trainings(training_items)
    training_items.select(&:finished).count
  end
end

app/helpers/training_plans_helper.rb
module TrainingPlansHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
  def can_be_deleted_by_user?(training)
    user_id = training.created_by
    user_id == current_user&.id
  end

  def append_database_field_before_create(hash)
    hash.merge( {created_by: current_user.id, total_distance: total_distance(hash[:content]) })
  end

  def total_distance(content)
    return 0 if !content || content.empty?
    lines = content.split("\n")
    lines.inject(0) do |sum,line|
      line = line.gsub(/\s+/, '')
      merged = line.scan(/\d+[x*]\d+/).join
      if merged.length != 0
        result =merged.split(/[x*]/)
        sum += result[0].to_i * result[1].to_i
      else
        sum += line[/\d+/].to_i
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(id)
    return nil unless id
    @user = User.find(id)
    {name: @user.name, profile_path: user_path(@user)}
  end

  def users_training_plan(user_id)
    user = User.find(user_id)
    if user
      TrainingPlan.find_or_create_by(user_id: user_id) do |plan|
        plan.name = "Default training plan for user #{user.name}"
      end
    end
  end
end

app/views/layouts/_footer.html.erb
Footer

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Swimming training planner", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help",  '#' %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "My training plan", training_plans_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "My training plan", training_plans_path %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwimmingTrainingPlanner</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>

  <% end %>
  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/training_plans/index.html.erb
<h1>Training plans</h1>
<li>
<% @training_plans.each do |plan| %>
    <ul>
       <%= link_to "#{plan.name}", training_plan_path(id: plan.id) %>
    </ul>
<% end %>
</li>

app/views/training_plans/show.html.erb
<h1><%= @training_plan.name %></h1>
  <%= link_to 'Choose training item from existing trainings', trainings_path, class: "btn btn-lg btn-primary center" %>
  <%= link_to 'Add new training', new_training_path, class: "btn btn-lg btn-primary center" %>

  <p>Total distance in completed trainings: <%= total_distance_in_completed_trainings(@training_plan.training_plan_items) %></p>
  <p>Total number of completed trainigns: <%= total_number_of_completed_trainings(@training_plan.training_plan_items) %></p>
  <table class="training-plan-items-table">
    <tr>
      <th>#</th>
      <th>Training id</th>
      <th>Training name</th>
      <th>Distance</th>
      <th>Date</th>
      <th>Status</th>
      <th>Training plan id</th>
      <th>Training plan</th>
      <th>Actions</th>
    </tr>
    <% @items.each_with_index do |item, index| %>
        <tr class="training-item">
          <td><%= index+1 %></td>
          <td><%= item.training.id %></td>
          <td><%= item.training.title %></td>
          <td><%= item.training.total_distance %></td>
          <td><%= item.date %></td>
          <td><%= training_plan_item_status(item) %></td>
          <td><%= item.training_plan.id %></td>
          <td><%= item.training_plan.name %></td>
          <td><%= link_to 'Delete', training_plan_item_path(item), method: :delete %></td>
          <td><%= link_to 'Edit', '#' %></td>
          <td>
            Mark finished:
            <%= check_box_tag 'checkbox', item.id, checked = item.finished, :class => 'checkbox', :id => item.id %>
          </td>
        </tr>
    <% end %>

  </table>

app/views/trainings/_training_item.html.erb
<div class="training-item">
  <div class="index">#<%= index %></div>
  <%= link_to training_path(training) do %>
      <div class="title"><%= training.title %></div>
  <% end %>
  <div class="content">
    <%= react_component("TrainingContent", {content: training.content, minimum_lines_to_display: 3}) %>
  </div>
  <div class="total-distance">Total: <%= training.total_distance %></div>
  <% if user_name(training.created_by) %>
      <div class="created-by">Added by:<%= link_to user_name(training.created_by)[:name],
                                                   user_name(training.created_by)[:profile_path] %>
      </div>
  <% end %>
  <% if can_be_deleted_by_user?(training) %>
      <%= link_to 'Delete this training', training_path(training), method: :delete %>
  <% end %>
  <% if user_signed_in? %>
      <p>
        <%= link_to 'Add to my training plan', add_training_path(training.id), method: :post %>
      </p>
  <% end %>

</div>

app/views/trainings/index.html.erb
<h1> Hello </h1>
<% if user_signed_in? %>
    <p>
      <%= link_to 'Add new training', new_training_path %>
    </p>
    <% else %>
    <div class="center jumbotron">
      <h3>If you want to add trainings to your training plans, please sign in or sign up!</h3>

      <%= link_to "Sign in!", new_user_session_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Sign up!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

<h2>Existing trainings</h2>
<% @trainings.each_with_index do |t, index| %>
        <%= render "training_item", training: t, index: index+1 %>
<% end %>

<% if user_signed_in? %>
    <p>
      <%= link_to 'Add new training', new_training_path %>
    </p>
<% end %>

app/views/trainings/new.html.erb
<h1>New Training</h1>
<%= form_for :training, url: trainings_path do |f| %>

    <% if @training.try(:errors).try(:any?) %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@training.errors.count, "error") %> prohibited
            this training from being saved:
          </h2>
          <ul>
            <% @training.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>
<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<h1>Training id: <%= @training.id %></h1>
<div name="training-item" >
  <div name="index">#<%= @training.id %></div>
  <div name="title"><%= @training.title %></div>
  <div name="content"><%= @training.content %></div>
  <div name="total-distance">Total: <%= @training.total_distance %></div>
  <div name="created-by">Added by:<%= @training.created_by %></div>
  <% link_to 'Add to my training plan', '#' %>
</div>

<%= link_to 'Back', trainings_path %>

app/views/users/index.html.erb
Users - index

app/views/users/show.html.erb
<h1>Profile page for: <%= @user.email %> </h1>

<h3>Username: <%= @user.name %> </h3>
<h3>Email: <%= @user.email %> </h3>
<h3>Joined: <%= @user.created_at&.to_date %> </h3>